# Generated by Django 4.0.4 on 2022-05-22 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 22, 14, 45, 43, 750815), null=True, verbose_name='Last donation date'),
        ),
    ]
