# Generated by Django 4.0.4 on 2022-05-22 17:50

import datetime
from django.db import migrations, models

# modif

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 1), null=True, verbose_name='Last donation date'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wdate0',
            field=models.DateField(default=datetime.date(2021, 1, 1), verbose_name='Date'),
        ),
    ]
