# Generated by Django 4.0.4 on 2022-06-02 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_profile_don_date_alter_weather_wdate0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wnday', models.IntegerField(default=0, verbose_name='Day number')),
                ('wdate', models.DateField(default=datetime.date(2021, 1, 1), verbose_name='Date')),
                ('wid', models.IntegerField(default=0, verbose_name='Weather code')),
                ('wmain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main')),
                ('wdescription', models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description')),
                ('wpressure', models.IntegerField(default=0, verbose_name='Pressure')),
                ('wtemp_min', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature')),
                ('wtemp_max', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature')),
                ('wwind_speed', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed')),
                ('wwind_gust', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed')),
                ('whumidity', models.IntegerField(default=0, verbose_name='Humidity')),
                ('wrain', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain')),
                ('wicon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
