# Generated by Django 4.0.2 on 2022-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_lat_profile_long_profile_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(decimal_places=6, default='48.856643', max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long',
            field=models.DecimalField(decimal_places=6, default='2.352566', max_digits=10, verbose_name='Longitude'),
        ),
    ]
