# Generated by Django 4.0.2 on 2022-05-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='don_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 17, 50, 57, 312213)),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_temp',
            field=models.IntegerField(default=30, verbose_name='Max temperature (°C)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_wind',
            field=models.IntegerField(default=50, verbose_name='Gust speed (km/h)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_temp',
            field=models.IntegerField(default=2, verbose_name='Min temperature (°C)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='valid_user',
            field=models.BooleanField(default=False, verbose_name='Valid user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weather',
            field=models.BooleanField(default=False, verbose_name='Weather alert'),
        ),
    ]
