# Generated by Django 4.0.4 on 2022-05-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_don_date_profile_max_temp_profile_max_wind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yt',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 17, 13, 0, 396122)),
        ),
    ]
