# Generated by Django 4.0.4 on 2022-05-08 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_expert_alter_profile_don_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 9, 23, 43, 858269)),
        ),
    ]
