# Generated by Django 4.0.4 on 2022-05-08 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_don_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Last donation date'),
        ),
    ]
