# Generated by Django 4.0.4 on 2022-05-08 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_unites_alter_profile_don_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 8, 17, 49, 43, 913878), null=True, verbose_name='Last donation date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_temp',
            field=models.IntegerField(default=30, verbose_name='Max temperature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_wind',
            field=models.IntegerField(default=50, verbose_name='Gust speed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_temp',
            field=models.IntegerField(default=2, verbose_name='Min temperature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unites',
            field=models.CharField(choices=[('1', 'Metric (°C, m/s)'), ('2', 'Imperial (°F, miles/hour)'), ('3', 'Standard (°K, m/s)')], default='1', max_length=1, verbose_name='Units'),
        ),
    ]
