# Generated by Django 4.0.4 on 2022-05-08 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_don_date_alter_profile_max_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 8, 17, 51, 27, 727875), null=True, verbose_name='Last donation date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_wind',
            field=models.IntegerField(default=15, verbose_name='Gust speed'),
        ),
    ]
