# Generated by Django 4.0.4 on 2022-05-09 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_weather_alter_profile_don_date_alter_profile_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='wdate',
            new_name='wdate0',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='wid',
            new_name='wid0',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='wnday',
            new_name='wnday0',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wdescription',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wicon',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wmain',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wtemp_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wtemp_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wwind_gust',
        ),
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='wdate1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdate2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdate3',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdate4',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdescription0',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdescription1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdescription2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdescription3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wdescription4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='whumidity0',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='whumidity1',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='whumidity2',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='whumidity3',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='whumidity4',
            field=models.IntegerField(default=0, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wicon0',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wicon1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wicon2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wicon3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wicon4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weather icon'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wid1',
            field=models.IntegerField(default=0, verbose_name='Weather code'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wid2',
            field=models.IntegerField(default=0, verbose_name='Weather code'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wid3',
            field=models.IntegerField(default=0, verbose_name='Weather code'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wid4',
            field=models.IntegerField(default=0, verbose_name='Weather code'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wmain0',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wmain1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wmain2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wmain3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wmain4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather main'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wnday1',
            field=models.IntegerField(default=0, verbose_name='Day number'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wnday2',
            field=models.IntegerField(default=0, verbose_name='Day number'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wnday3',
            field=models.IntegerField(default=0, verbose_name='Day number'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wnday4',
            field=models.IntegerField(default=0, verbose_name='Day number'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wpressure0',
            field=models.IntegerField(default=0, verbose_name='Pressure'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wpressure1',
            field=models.IntegerField(default=0, verbose_name='Pressure'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wpressure2',
            field=models.IntegerField(default=0, verbose_name='Pressure'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wpressure3',
            field=models.IntegerField(default=0, verbose_name='Pressure'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wpressure4',
            field=models.IntegerField(default=0, verbose_name='Pressure'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_max0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_max1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_max2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_max3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_max4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Max temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_min0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_min1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_min2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_min3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wtemp_min4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Min temperature'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_gust0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_gust1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_gust2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_gust3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_gust4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Gusts speed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 9, 17, 56, 24, 47707), null=True, verbose_name='Last donation date'),
        ),
    ]
