# Generated by Django 4.0.4 on 2022-05-10 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_wdate_weather_wdate0_rename_wid_weather_wid0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wwind_speed0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_speed1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_speed2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_speed3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wwind_speed4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Wind speed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 10, 19, 49, 43, 82111), null=True, verbose_name='Last donation date'),
        ),
    ]
