# Generated by Django 4.0.4 on 2022-05-11 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_weather_wwind_speed0_weather_wwind_speed1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wrain0',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wrain1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wrain2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wrain3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wrain4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Rain'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 11, 19, 50, 17, 913024), null=True, verbose_name='Last donation date'),
        ),
    ]
