# Generated by Django 4.0.4 on 2022-05-18 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_weather_wrain0_weather_wrain1_weather_wrain2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='alert_description',
            field=models.TextField(blank=True, null=True, verbose_name='Alert description'),
        ),
        migrations.AddField(
            model_name='weather',
            name='alert_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='weather',
            name='alert_event',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='weather',
            name='alert_sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alert sender'),
        ),
        migrations.AddField(
            model_name='weather',
            name='alert_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 18, 18, 0, 28, 7007), null=True, verbose_name='Last donation date'),
        ),
    ]
