# Generated by Django 4.0.4 on 2022-05-20 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_weather_alert_description_weather_alert_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 20, 13, 45, 36, 778267), null=True, verbose_name='Last donation date'),
        ),
    ]
