# Generated by Django 4.0.4 on 2022-05-21 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_web_alter_profile_don_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='unites',
            field=models.CharField(default='1', max_length=1, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='don_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 21, 14, 26, 31, 756423), null=True, verbose_name='Last donation date'),
        ),
    ]
