# Generated by Django 4.0.4 on 2022-05-22 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(default='A', max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('cat', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Planting date')),
                ('adate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Acquisition date')),
                ('treePic', models.ImageField(default='default.png', upload_to='tree_pics', verbose_name='Main picture')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL (YouTube video...)')),
                ('originfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.origin', verbose_name='Origin')),
                ('ownerfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('speciesfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.species', verbose_name='Species')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='Planned date')),
                ('real_date', models.DateField(blank=True, null=True, verbose_name='Realisation date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL (YouTube video...)')),
                ('tasklistfk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.tasklist', verbose_name='Type')),
                ('treefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tree', verbose_name='Tree')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('shot_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Shot date')),
                ('before_pic', models.BooleanField(default=False, verbose_name='Shot before task')),
                ('after_pic', models.BooleanField(default=False, verbose_name='Shot after task')),
                ('picture', models.ImageField(upload_to='trees-tasks_pics', verbose_name='Picture')),
                ('thumb', models.ImageField(default='thumbs/default-thumb.png', upload_to='thumbs', verbose_name='Thumbnail')),
                ('taskfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Task')),
                ('treefk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tree', verbose_name='Tree')),
            ],
        ),
    ]
