# Generated by Django 4.0.2 on 2022-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='name',
            new_name='tname',
        ),
    ]
