# Generated by Django 4.0.4 on 2022-06-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linkcat_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lang', models.CharField(default='EN', max_length=4, verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='lang',
            field=models.CharField(default='EN', max_length=4, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.IntegerField(default=10, verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('order', models.IntegerField(default=10, verbose_name='Order')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('image', models.ImageField(upload_to='links_pics', verbose_name='Logo')),
                ('video', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('faqcatfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faqcat', verbose_name='Category')),
            ],
        ),
    ]
