# Generated by Django 4.0.2 on 2022-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_owner_tree_ownerfk_alter_tree_adate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='shop',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
