# Generated by Django 4.0.4 on 2022-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faqcat_link_lang_alter_link_order_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='links_pics', verbose_name='Logo'),
        ),
    ]
