# Generated by Django 4.0.2 on 2022-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tree_description_alter_tree_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='adate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='shop',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
