# Generated by Django 4.0.2 on 2022-03-21 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tree_adate_alter_tree_bdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='adate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
