# Generated by Django 4.0.2 on 2022-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tree_adate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='treePic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
