# Generated by Django 4.0.2 on 2022-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tree_treepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='treePic',
            field=models.ImageField(default='default.png', upload_to='tree_pics'),
        ),
    ]
