# Generated by Django 4.0.2 on 2022-03-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_tree_treepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='adate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Acquisition date'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Planting date'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='ownerfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='shop',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shop/ex-owner'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='speciesfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.species', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tname',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='treePic',
            field=models.ImageField(default='default.png', upload_to='tree_pics', verbose_name='Main picture'),
        ),
    ]
