# Generated by Django 4.0.2 on 2022-04-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_origin_remove_tree_shop_alter_tree_speciesfk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlname', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasklistfk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.tasklist', verbose_name='Type')),
                ('treefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tree', verbose_name='Tree')),
            ],
        ),
    ]
