# Generated by Django 4.0.2 on 2022-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tasklist_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned date'),
        ),
        migrations.AddField(
            model_name='task',
            name='real_date',
            field=models.DateField(blank=True, null=True, verbose_name='Realisation date'),
        ),
    ]
