# Generated by Django 4.0.2 on 2022-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL (YouTube video...)'),
        ),
        migrations.AddField(
            model_name='tree',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL (YouTube video...)'),
        ),
    ]
