# Generated by Django 4.0.2 on 2022-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_url_tree_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='url',
            new_name='urltask',
        ),
    ]
