# Generated by Django 4.0.2 on 2022-04-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_url_task_urltask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='urltask',
            new_name='url',
        ),
    ]
