# Generated by Django 4.0.2 on 2022-04-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_urltask_task_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('shot_date', models.DateField(blank=True, null=True, verbose_name='Shot date')),
                ('before_pic', models.BooleanField(default=False, verbose_name='Shot before task')),
                ('after_pic', models.BooleanField(default=False, verbose_name='Shot after task')),
                ('picture', models.ImageField(upload_to='trees-tasks_pics', verbose_name='Picture')),
                ('thumb', models.ImageField(upload_to='trees-tasks_pics', verbose_name='Thumbnail')),
                ('taskfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Task')),
                ('treefk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tree', verbose_name='Tree')),
            ],
        ),
    ]
