# Generated by Django 4.0.2 on 2022-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_photo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs', verbose_name='Thumbnail'),
        ),
    ]
