# Generated by Django 4.0.2 on 2022-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_photo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(default='thumbs/default-thumb.png', upload_to='thumbs', verbose_name='Thumbnail'),
        ),
    ]
