# Generated by Django 4.0.2 on 2022-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_photo_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='sname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='species',
            name='cat',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
