# Generated by Django 4.0.2 on 2022-04-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_sname_species_name_species_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('cat', 'name')},
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='oname',
            new_name='name',
        ),
    ]
