# Generated by Django 4.0.2 on 2022-04-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_species_options_rename_oname_origin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='tlname',
            new_name='name',
        ),
    ]
