# Generated by Django 4.0.2 on 2022-04-23 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_tlname_tasklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='shot_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Shot date'),
        ),
    ]
